// generated by Fast Light User Interface Designer (fluid) version 1.0300

#ifndef test_ui_h
#define test_ui_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Scroll.H>
#include <FL/Fl_Spinner.H>
#include <FL/Fl_Button.H>

class TestUI {
public:
  TestUI();
};
#endif
